name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GO111MODULE: on

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        go: ["1.11.x", "1.12.x", "1.13.x", "1.14.x", "1.15.x", "1.16.x", "1.17.x" ]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test -v ./...

    - name: Test with race
      run: go test -timeout 10m -v -race ./...
